remote_theme: daattali/beautiful-jekyll@5.0.0

title: dekelpilli
author: Dekel Pilli

navbar-links:
  about: "about"
  Resources:
    - Repositories: "https://github.com/dekelpilli?tab=repositories"
    - Resumè: "assets/dl/resume.pdf"

social-network-links:
  email: "dekelpilli@gmail.com"
  github: dekelpilli
  linkedin: dekelpilli

date_format: "%Y-%m-%d"

share-links-active:
  twitter: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      social-share: true
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"
